In [5]:
from pyxlsb import open_workbook
import pandas as pd

def convert_xlsb_to_xlsx(xlsb_path,xlsx_path):
    with open_workbook(xlsb_path) as wb:
        with wb.get_sheet(1) as sheet:
            data=[[item.v for item in row] for row in sheet.rows()]

    df=pd.DataFrame(data[1:],columns=data[0])

    df.to_excel(xlsx_path,index=False)

convert_xlsb_to_xlsx(r'C:\Users\Dell\Downloads\Norm DJSJ.xlsb',r'C:\Users\Dell\Documents\Norm.xlsx')

In [1]:
import numpy as np
import pandas as pd

In [25]:
stock= pd.read_csv(r'D:\GdriveBackup\0.Projects\Mock Projects\DE\Python\stock.csv')
stock.dropna(how='all').sample(10).sort_index()

,IndexColumn,InventSerialId,itemid,wmslocationid,InventSiteId,DataAreaId,WH,Gross Weight,Metal_Wt,Gold cost,...,Vendor Name,Age Band,Geo Cluster,Other Wt,Other Material,Other Selling Price,Price Band,Production Order remarks,MRP,Expiry Date
7,590,1502752,TPH21017-D000X0H,Sellable,308,ofcl,NaN,0.63,0.256,508.00896,...,SAPPHIRESKY JEWELS LLP.,242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,6477,1581554,MRG08010-D400RNC,Sellable,303,ofcl,NaN,7.03,7.022,21171.33000,...,Kantilal Chhotalal,133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,7724,1601701,OPS18018-D400R0C,Sellable,303,ofcl,NaN,4.12,4.052,12476.15000,...,NaN,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,9468,1626679,OIC18034-D000YEB,Sellable,303,ofcl,NaN,4.15,4.150,16052.20000,...,NaN,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,9569,1628135,OPE16063-D400R0C,Sellable,304,ofcl,NaN,2.00,1.942,5902.24000,...,NaN,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
571,10109,1638089,OBO13025-D200REB,Sellable,304,ofcl,NaN,17.87,17.706,69048.09000,...,NaN,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
579,10269,1640544,ORG22104-D400XHC,Sellable,308,ofcl,NaN,3.50,3.400,10017.45000,...,NaN,242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,10385,1642120,OBG18134-D200REB,Sellable,308,ofcl,NaN,19.23,18.934,72663.57982,...,NaN,242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
706,10868,1650216,MRG20005-D200RJB,URD,308,ofcl,NaN,5.65,5.568,21271.71000,...,SAPPHIRESKY JEWELS LLP.,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
713,10892,1650355,PMR19035-D200OPD,Sellable,303,ofcl,NaN,7.50,7.478,8282.52000,...,NaN,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
stock=stock[stock['wmslocationid']=='Sellable']

In [22]:
stock.select_dtypes(include='object')

,itemid,wmslocationid,DataAreaId,Design_NO,Brand,Product Group,Sub Product Group,Product Category,Sub Category,Parent Product Category,...,Store In Date,GRN Date,Active Promotion,PO Number,Procurement Type,Manufacturing Vendor,Manufacturing Vendor name,Stock in Date,Vendor Code,Vendor Name
0,TPH21010-D000X0H,Sellable,ofcl,TPH21010,Orra,Proto,Plain,Peg Head,General,Other,...,2024-03-31 12:00:00.0000000,2021-07-08 12:00:00.0000000,GJ Offer,PO_000003818,Franchise Return,VEND-00018,H.K. Jewels Pvt. Ltd.,2024-03-31 12:00:00.0000000,VEND-07172,SAPPHIRESKY JEWELS LLP.
1,TPH21011-D000X0H,Sellable,ofcl,TPH21011,Orra,Proto,Plain,Peg Head,General,Other,...,2024-03-31 12:00:00.0000000,2021-07-08 12:00:00.0000000,GJ Offer,PO_000003818,Franchise Return,VEND-00018,H.K. Jewels Pvt. Ltd.,2024-03-31 12:00:00.0000000,VEND-07172,SAPPHIRESKY JEWELS LLP.
2,TPH21012-D000X0H,Sellable,ofcl,TPH21012,Orra,Proto,Studded,Peg Head,General,Other,...,2024-03-31 12:00:00.0000000,2021-07-08 12:00:00.0000000,GJ Offer,PO_000003818,Franchise Return,VEND-00018,H.K. Jewels Pvt. Ltd.,2024-03-31 12:00:00.0000000,VEND-07172,SAPPHIRESKY JEWELS LLP.
3,TPH21013-D000X0H,Sellable,ofcl,TPH21013,Orra,Proto,Plain,Peg Head,General,Other,...,2024-03-31 12:00:00.0000000,2021-07-08 12:00:00.0000000,GJ Offer,PO_000003818,Franchise Return,VEND-00018,H.K. Jewels Pvt. Ltd.,2024-03-31 12:00:00.0000000,VEND-07172,SAPPHIRESKY JEWELS LLP.
4,TPH21014-D000X0H,Sellable,ofcl,TPH21014,Orra,Proto,Plain,Peg Head,General,Other,...,2024-03-31 12:00:00.0000000,2021-07-08 12:00:00.0000000,GJ Offer,PO_000003818,Franchise Return,VEND-00018,H.K. Jewels Pvt. Ltd.,2024-03-31 12:00:00.0000000,VEND-07172,SAPPHIRESKY JEWELS LLP.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,OBF19033-D400REC,Sellable,ofcl,OBF19033,Orra,Diamond Jewelry,Studded,Bracelet,General,Bracelet,...,2024-01-22 12:00:00.0000000,2022-10-13 12:00:00.0000000,DJ Studded Slab Offer,NaN,NaN,VEND-00027,KGK Creations ( INDIA) Pvt. Ltd,NaN,NaN,NaN
996,GMR22025-N1B0YLA,Sellable,ofcl,GMR22025,Orra,Gold Jewelry,Plain,Ring,General,Ring,...,2024-01-22 12:00:00.0000000,2022-10-14 12:00:00.0000000,GJ Offer,NaN,NaN,VEND-00057,Shineshilpi Jewellers Pvt. Ltd,NaN,NaN,NaN
997,OSN22188-D308R0B,URD,ofcl,OSN22188,Orra,Diamond Jewelry,Studded,Set Necklace,Haram,Neckwear Set,...,2024-10-12 12:00:00.0000000,2022-10-14 12:00:00.0000000,DJ Studded Slab Offer,NaN,NaN,VEND-00008,AURA JEWELS,NaN,NaN,NaN
998,OPE18072-D400X0C,Sellable,ofcl,OPE18072,Orra,Diamond Jewelry,Studded,Pendant Earring,General,Pendant Set,...,2024-03-27 12:00:00.0000000,2022-10-14 12:00:00.0000000,Value Pickup DJ,PO_000004962,NaN,VEND-02996,Laxmi Dia Jewels Pvt.Ltd. Astra,2024-03-27 12:00:00.0000000,NaN,NaN
999,OAC07021-D000YSB,URD,ofcl,OAC07021,Orra,Diamond Jewelry,Plain,Chain,General,Chain,...,2024-10-12 12:00:00.0000000,2022-10-14 12:00:00.0000000,Gold Chain-18KT-14KT,NaN,NaN,VEND-00008,AURA JEWELS,NaN,NaN,NaN

In [ ]:
from pyspark.sql import SparkSession

# Create a Spark session
spark = SparkSession.builder \
    .appName("MyPySparkApp") \
    .config("spark.sql.shuffle.partitions", "200") \
    .config("spark.executor.memory", "4g") \
    .config("spark.driver.memory", "4g") \
    .getOrCreate()

In [30]:
stockdf= spark.read.csv(r'D:\GdriveBackup\0.Projects\Mock Projects\DE\Python\stock.csv',header=True,inferSchema=True)
stockdf.show(truncate=False)

+-----------+--------------+----------------+-------------+------------+----------+----+------------+--------+---------+-----------+------------+----------+-------------+--------------+-----------+------------------+--------------------+----------------------+---------------------+-------------------+--------------------+-----------+----------+-------------+----------+----------+----------+---------+-----+-------------+-----------------+----------------+------------+-----------------------+------+---------+-----------+---------------+--------+------------+----------+------------------+-------------+--------------------+----------+------------+---------------------+----+----------+---------+------+----------+------------+------------+------------------------------+-----------+-------------+----------+---------------+----------------+------------+--------------+------------+----------+--------------+------+-----------------+-------------------+----------------------+-----------+---------------------+-----------+----------+----------------+--------------+--------------+-------------------+------------+-----------------+---------------+-------------------+-------------------+----------------+------------+----------------+--------------------+-------------------------+---------------------------+-----------+-----------------------+--------+-----------+--------+--------------+-------------------+----------+------------------------+----+-----------+
|IndexColumn|InventSerialId|itemid          |wmslocationid|InventSiteId|DataAreaId|WH  |Gross Weight|Metal_Wt|Gold cost|Silver Cost|Diamond Cost|Stone Cost|Platinum Cost|Wastage Amount|Making Cost|Gold Selling Price|Silver Selling Price|Platinum Selling Price|Diamond Selling Price|Stone Selling Price|Making Selling Price|Making Rate|Cost_Price|Selling_Price|Other Cost|IGI Amount|PGI Amount|Design_NO|Brand|Product Group|Sub Product Group|Product Category|Sub Category|Parent Product Category|Gender|Sub-Brand|Workmanship|Sub-Workmanship|Occasion|Design Motif|Collection|Incentive Category|Design Region|Diamond Setting Type|Stone Type|Metal Finish|Diamond Color Clarity|Size|Size Index|Size Unit|Purity|Child Unit|Store Type  |Store Region|Warehouse Name                |Gold Weight|Silver Weight|Diamond_Wt|Platinum Weight|Palladium Weight|Stone Weight|Diamond Pieces|Stone Pieces|Gold Color|Platinum Color|CW Qty|Gold Selling Rate|Silver Selling Rate|Platinum  Selling Rate|Weight Band|Stock Location Remark|Transfer ID|TO Created|TO From Location|TO to Location|FROM Warehouse|FROM Warehouse Name|To Warehouse|TO Warehouse Name|Advance Booking|Store In Date      |GRN Date           |Active Promotion|PO Number   |Procurement Type|Manufacturing Vendor|Manufacturing Vendor name|Stock in Date              |Vendor Code|Vendor Name            |Age Band|Geo Cluster|Other Wt|Other Material|Other Selling Price|Price Band|Production Order remarks|MRP |Expiry Date|
+-----------+--------------+----------------+-------------+------------+----------+----+------------+--------+---------+-----------+------------+----------+-------------+--------------+-----------+------------------+--------------------+----------------------+---------------------+-------------------+--------------------+-----------+----------+-------------+----------+----------+----------+---------+-----+-------------+-----------------+----------------+------------+-----------------------+------+---------+-----------+---------------+--------+------------+----------+------------------+-------------+--------------------+----------+------------+---------------------+----+----------+---------+------+----------+------------+------------+------------------------------+-----------+-------------+----------+---------------+----------------+------------+--------------+------------+----------+--------------+------+-----------------+-------------------+----------------------+-----------+---------------------+-----------+----------+----------------+--------------+--------------+-------------------+------------+-----------------+---------------+-------------------+-------------------+----------------+------------+----------------+--------------------+-------------------------+---------------------------+-----------+-----------------------+--------+-----------+--------+--------------+-------------------+----------+------------------------+----+-----------+
|353        |1502507       |TPH21010-D000X0H|Sellable     |308         |ofcl      |NULL|0.44        |0.44    |0.0      |0.0        |0.0         |0.0       |0.0          |0.0           |0.0        |0.0               |0.0                 |0.0                   |0.0                  |0.0                |0.0                 |0.0        |1938.0    |1692.24      |0.0       |0.0       |0.0       |TPH21010 |Orra |Proto        |Plain            |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|0.88       |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |0.000000         |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-00018          |H.K. Jewels Pvt. Ltd.    |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |
|387        |1502542       |TPH21011-D000X0H|Sellable     |308         |ofcl      |NULL|0.376       |0.376   |0.0      |0.0        |0.0         |0.0       |0.0          |0.0           |0.0        |0.0               |0.0                 |0.0                   |0.0                  |0.0                |0.0                 |0.0        |1811.0    |1446.1       |0.0       |0.0       |0.0       |TPH21011 |Orra |Proto        |Plain            |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|0.752      |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |0.000000         |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-00018          |H.K. Jewels Pvt. Ltd.    |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |
|421        |1502577       |TPH21012-D000X0H|Sellable     |308         |ofcl      |NULL|0.66        |0.66    |0.0      |0.0        |0.0         |0.0       |0.0          |0.0           |0.0        |0.0               |0.0                 |0.0                   |0.0                  |0.0                |0.0                 |0.0        |2375.0    |2538.36      |0.0       |0.0       |0.0       |TPH21012 |Orra |Proto        |Studded          |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|1.32       |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |0.000000         |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-00018          |H.K. Jewels Pvt. Ltd.    |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |
|455        |1502612       |TPH21013-D000X0H|Sellable     |308         |ofcl      |NULL|0.132       |0.132   |0.0      |0.0        |0.0         |0.0       |0.0          |0.0           |0.0        |0.0               |0.0                 |0.0                   |0.0                  |0.0                |0.0                 |0.0        |1327.0    |507.67       |0.0       |0.0       |0.0       |TPH21013 |Orra |Proto        |Plain            |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|0.264      |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |0.000000         |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-00018          |H.K. Jewels Pvt. Ltd.    |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |
|488        |1502647       |TPH21014-D000X0H|Sellable     |308         |ofcl      |NULL|0.17        |0.17    |0.0      |0.0        |0.0         |0.0       |0.0          |0.0           |0.0        |0.0               |0.0                 |0.0                   |0.0                  |0.0                |0.0                 |0.0        |1402.0    |653.82       |0.0       |0.0       |0.0       |TPH21014 |Orra |Proto        |Plain            |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|0.51       |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |0.000000         |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-00018          |H.K. Jewels Pvt. Ltd.    |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |
|522        |1502682       |TPH21015-D000X0H|Sellable     |308         |ofcl      |NULL|0.51        |0.15    |297.6615 |0.0        |30.0        |0.0       |0.0          |0.0           |1000.0     |355.5             |0.0                 |0.0                   |350857.8             |0.0                |0.0                 |1000.0     |1362.6615 |1370.0       |0.0       |0.0       |0.0       |TPH21015 |Orra |Proto        |Plain            |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|0.3        |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |1185.000000      |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-07118          |HARE KRISHNA SOLUTIONS   |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |
|556        |1502717       |TPH21016-D000X0H|Sellable     |308         |ofcl      |NULL|0.69        |0.336   |666.76176|0.0        |30.0        |0.0       |0.0          |0.0           |1000.0     |796.32            |0.0                 |0.0                   |345010.17            |0.0                |0.0                 |1000.0     |1731.76176|1740.0       |0.0       |0.0       |0.0       |TPH21016 |Orra |Proto        |Studded          |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|0.672      |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |1185.000000      |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-07118          |HARE KRISHNA SOLUTIONS   |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |
|590        |1502752       |TPH21017-D000X0H|Sellable     |308         |ofcl      |NULL|0.63        |0.256   |508.00896|0.0        |30.0        |0.0       |0.0          |0.0           |1000.0     |606.72            |0.0                 |0.0                   |364502.27            |0.0                |0.0                 |1000.0     |1573.00896|1580.0       |0.0       |0.0       |0.0       |TPH21017 |Orra |Proto        |Studded          |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|0.512      |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |1185.000000      |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-07118          |HARE KRISHNA SOLUTIONS   |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |
|624        |1502787       |TPH21018-D000X0H|Sellable     |308         |ofcl      |NULL|0.336       |0.336   |0.0      |0.0        |0.0         |0.0       |0.0          |0.0           |0.0        |0.0               |0.0                 |0.0                   |0.0                  |0.0                |0.0                 |0.0        |1732.0    |1292.26      |0.0       |0.0       |0.0       |TPH21018 |Orra |Proto        |Studded          |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|1.016      |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |0.000000         |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-00018          |H.K. Jewels Pvt. Ltd.    |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |
|658        |1502822       |TPH21019-D000X0H|Sellable     |308         |ofcl      |NULL|0.16        |0.16    |0.0      |0.0        |0.0         |0.0       |0.0          |0.0           |0.0        |0.0               |0.0                 |0.0                   |0.0                  |0.0                |0.0                 |0.0        |1383.0    |615.36       |0.0       |0.0       |0.0       |TPH21019 |Orra |Proto        |Plain            |Peg Head        |General     |Other                  |Women |General  |Casting    |NULL           |NULL    |NULL        |General   |DJ                |NULL         |NULL                |NULL      |Gold        |NULL                 |NULL|NULL      |NULL     |10K   |NULL      |Large Format|North       |Sapphiresky Jewels LLP-Lucknow|0.32       |0.0          |0.0       |0.0            |0.0             |0.0         |0.0           |0.0         |Pink      |NULL          |1     |0.000000         |NULL               |NULL                  |0-2 gms    |Store                |NULL       |NULL      |NULL            |NULL          |NULL          |NULL               |NULL        |NULL             |NULL           |2024-03-31 12:00:00|2021-07-08 12:00:00|GJ Offer        |PO_000003818|Franchise Return|VEND-00018          |H.K. Jewels Pvt. Ltd.    |2024-03-31 12:00:00.0000000|VEND-07172 |SAPPHIRESKY JEWELS LLP.|242     |NULL       |NULL    |NULL          |NULL               |NULL      |NULL                    |NULL|NULL       |

In [34]:
# Sample 10 rows randomly (using fraction)
sampled_df = stockdf.sample(withReplacement=False, fraction=1.0)

# Take the first 10 rows from the sampled DataFrame
sampled_df.limit(10).show()

+-----------+--------------+----------------+-------------+------------+----------+----+------------+--------+---------+-----------+------------+----------+-------------+--------------+-----------+------------------+--------------------+----------------------+---------------------+-------------------+--------------------+-----------+----------+-------------+----------+----------+----------+---------+-----+-------------+-----------------+----------------+------------+-----------------------+------+---------+-----------+---------------+--------+------------+----------+------------------+-------------+--------------------+----------+------------+---------------------+----+----------+---------+------+----------+------------+------------+--------------------+-----------+-------------+----------+---------------+----------------+------------+--------------+------------+----------+--------------+------+-----------------+-------------------+----------------------+-----------+---------------------+-----------+----------+----------------+--------------+--------------+-------------------+------------+-----------------+---------------+-------------------+-------------------+----------------+------------+----------------+--------------------+-------------------------+--------------------+-----------+--------------------+--------+-----------+--------+--------------+-------------------+----------+------------------------+----+-----------+
|IndexColumn|InventSerialId|          itemid|wmslocationid|InventSiteId|DataAreaId|  WH|Gross Weight|Metal_Wt|Gold cost|Silver Cost|Diamond Cost|Stone Cost|Platinum Cost|Wastage Amount|Making Cost|Gold Selling Price|Silver Selling Price|Platinum Selling Price|Diamond Selling Price|Stone Selling Price|Making Selling Price|Making Rate|Cost_Price|Selling_Price|Other Cost|IGI Amount|PGI Amount|Design_NO|Brand|Product Group|Sub Product Group|Product Category|Sub Category|Parent Product Category|Gender|Sub-Brand|Workmanship|Sub-Workmanship|Occasion|Design Motif|Collection|Incentive Category|Design Region|Diamond Setting Type|Stone Type|Metal Finish|Diamond Color Clarity|Size|Size Index|Size Unit|Purity|Child Unit|  Store Type|Store Region|      Warehouse Name|Gold Weight|Silver Weight|Diamond_Wt|Platinum Weight|Palladium Weight|Stone Weight|Diamond Pieces|Stone Pieces|Gold Color|Platinum Color|CW Qty|Gold Selling Rate|Silver Selling Rate|Platinum  Selling Rate|Weight Band|Stock Location Remark|Transfer ID|TO Created|TO From Location|TO to Location|FROM Warehouse|FROM Warehouse Name|To Warehouse|TO Warehouse Name|Advance Booking|      Store In Date|           GRN Date|Active Promotion|   PO Number|Procurement Type|Manufacturing Vendor|Manufacturing Vendor name|       Stock in Date|Vendor Code|         Vendor Name|Age Band|Geo Cluster|Other Wt|Other Material|Other Selling Price|Price Band|Production Order remarks| MRP|Expiry Date|
+-----------+--------------+----------------+-------------+------------+----------+----+------------+--------+---------+-----------+------------+----------+-------------+--------------+-----------+------------------+--------------------+----------------------+---------------------+-------------------+--------------------+-----------+----------+-------------+----------+----------+----------+---------+-----+-------------+-----------------+----------------+------------+-----------------------+------+---------+-----------+---------------+--------+------------+----------+------------------+-------------+--------------------+----------+------------+---------------------+----+----------+---------+------+----------+------------+------------+--------------------+-----------+-------------+----------+---------------+----------------+------------+--------------+------------+----------+--------------+------+-----------------+-------------------+----------------------+-----------+---------------------+-----------+----------+----------------+--------------+--------------+-------------------+------------+-----------------+---------------+-------------------+-------------------+----------------+------------+----------------+--------------------+-------------------------+--------------------+-----------+--------------------+--------+-----------+--------+--------------+-------------------+----------+------------------------+----+-----------+
|        353|       1502507|TPH21010-D000X0H|     Sellable|         308|      ofcl|NULL|        0.44|    0.44|      0.0|        0.0|         0.0|       0.0|          0.0|           0.0|        0.0|               0.0|                 0.0|                   0.0|                  0.0|                0.0|                 0.0|        0.0|    1938.0|      1692.24|       0.0|       0.0|       0.0| TPH21010| Orra|        Proto|            Plain|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|       0.88|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|         0.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-00018|     H.K. Jewels Pvt. ...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|
|        387|       1502542|TPH21011-D000X0H|     Sellable|         308|      ofcl|NULL|       0.376|   0.376|      0.0|        0.0|         0.0|       0.0|          0.0|           0.0|        0.0|               0.0|                 0.0|                   0.0|                  0.0|                0.0|                 0.0|        0.0|    1811.0|       1446.1|       0.0|       0.0|       0.0| TPH21011| Orra|        Proto|            Plain|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|      0.752|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|         0.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-00018|     H.K. Jewels Pvt. ...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|
|        421|       1502577|TPH21012-D000X0H|     Sellable|         308|      ofcl|NULL|        0.66|    0.66|      0.0|        0.0|         0.0|       0.0|          0.0|           0.0|        0.0|               0.0|                 0.0|                   0.0|                  0.0|                0.0|                 0.0|        0.0|    2375.0|      2538.36|       0.0|       0.0|       0.0| TPH21012| Orra|        Proto|          Studded|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|       1.32|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|         0.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-00018|     H.K. Jewels Pvt. ...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|
|        455|       1502612|TPH21013-D000X0H|     Sellable|         308|      ofcl|NULL|       0.132|   0.132|      0.0|        0.0|         0.0|       0.0|          0.0|           0.0|        0.0|               0.0|                 0.0|                   0.0|                  0.0|                0.0|                 0.0|        0.0|    1327.0|       507.67|       0.0|       0.0|       0.0| TPH21013| Orra|        Proto|            Plain|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|      0.264|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|         0.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-00018|     H.K. Jewels Pvt. ...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|
|        488|       1502647|TPH21014-D000X0H|     Sellable|         308|      ofcl|NULL|        0.17|    0.17|      0.0|        0.0|         0.0|       0.0|          0.0|           0.0|        0.0|               0.0|                 0.0|                   0.0|                  0.0|                0.0|                 0.0|        0.0|    1402.0|       653.82|       0.0|       0.0|       0.0| TPH21014| Orra|        Proto|            Plain|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|       0.51|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|         0.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-00018|     H.K. Jewels Pvt. ...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|
|        522|       1502682|TPH21015-D000X0H|     Sellable|         308|      ofcl|NULL|        0.51|    0.15| 297.6615|        0.0|        30.0|       0.0|          0.0|           0.0|     1000.0|             355.5|                 0.0|                   0.0|             350857.8|                0.0|                 0.0|     1000.0| 1362.6615|       1370.0|       0.0|       0.0|       0.0| TPH21015| Orra|        Proto|            Plain|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|        0.3|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|      1185.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-07118|     HARE KRISHNA SOLU...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|
|        556|       1502717|TPH21016-D000X0H|     Sellable|         308|      ofcl|NULL|        0.69|   0.336|666.76176|        0.0|        30.0|       0.0|          0.0|           0.0|     1000.0|            796.32|                 0.0|                   0.0|            345010.17|                0.0|                 0.0|     1000.0|1731.76176|       1740.0|       0.0|       0.0|       0.0| TPH21016| Orra|        Proto|          Studded|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|      0.672|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|      1185.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-07118|     HARE KRISHNA SOLU...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|
|        590|       1502752|TPH21017-D000X0H|     Sellable|         308|      ofcl|NULL|        0.63|   0.256|508.00896|        0.0|        30.0|       0.0|          0.0|           0.0|     1000.0|            606.72|                 0.0|                   0.0|            364502.27|                0.0|                 0.0|     1000.0|1573.00896|       1580.0|       0.0|       0.0|       0.0| TPH21017| Orra|        Proto|          Studded|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|      0.512|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|      1185.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-07118|     HARE KRISHNA SOLU...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|
|        624|       1502787|TPH21018-D000X0H|     Sellable|         308|      ofcl|NULL|       0.336|   0.336|      0.0|        0.0|         0.0|       0.0|          0.0|           0.0|        0.0|               0.0|                 0.0|                   0.0|                  0.0|                0.0|                 0.0|        0.0|    1732.0|      1292.26|       0.0|       0.0|       0.0| TPH21018| Orra|        Proto|          Studded|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|      1.016|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|         0.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-00018|     H.K. Jewels Pvt. ...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|
|        658|       1502822|TPH21019-D000X0H|     Sellable|         308|      ofcl|NULL|        0.16|    0.16|      0.0|        0.0|         0.0|       0.0|          0.0|           0.0|        0.0|               0.0|                 0.0|                   0.0|                  0.0|                0.0|                 0.0|        0.0|    1383.0|       615.36|       0.0|       0.0|       0.0| TPH21019| Orra|        Proto|            Plain|        Peg Head|     General|                  Other| Women|  General|    Casting|           NULL|    NULL|        NULL|   General|                DJ|         NULL|                NULL|      NULL|        Gold|                 NULL|NULL|      NULL|     NULL|   10K|      NULL|Large Format|       North|Sapphiresky Jewel...|       0.32|          0.0|       0.0|            0.0|             0.0|         0.0|           0.0|         0.0|      Pink|          NULL|     1|         0.000000|               NULL|                  NULL|    0-2 gms|                Store|       NULL|      NULL|            NULL|          NULL|          NULL|               NULL|        NULL|             NULL|           NULL|2024-03-31 12:00:00|2021-07-08 12:00:00|        GJ Offer|PO_000003818|Franchise Return|          VEND-00018|     H.K. Jewels Pvt. ...|2024-03-31 12:00:...| VEND-07172|SAPPHIRESKY JEWEL...|     242|       NULL|    NULL|          NULL|               NULL|      NULL|                    NULL|NULL|       NULL|

In [1]:
import pandas as pd
import numpy as np

def straight_line_amortization(principal, annual_rate, years):
    """
    Create a straight-line amortization schedule
    
    Args:
    principal (float): Total loan amount
    annual_rate (float): Annual interest rate
    years (int): Loan tenure in years
    
    Returns:
    pandas.DataFrame: Amortization schedule
    """
    # Calculations
    annual_principal = principal / years
    periods = years
    
    # Initialize lists to store schedule data
    payment_num = []
    begin_balance = []
    principal_payment = []
    interest_payment = []
    total_payment = []
    end_balance = []
    
    # Current balance starts at principal
    current_balance = principal
    
    for period in range(1, periods + 1):
        # Interest is calculated on remaining balance
        interest = current_balance * annual_rate
        
        # Principal payment is fixed
        current_principal = annual_principal
        
        # Total payment
        current_total = current_principal + interest
        
        # Track data
        payment_num.append(period)
        begin_balance.append(current_balance)
        principal_payment.append(current_principal)
        interest_payment.append(interest)
        total_payment.append(current_total)
        
        # Reduce balance
        current_balance -= current_principal
        end_balance.append(current_balance)
    
    # Create DataFrame
    df = pd.DataFrame({
        'Payment Number': payment_num,
        'Beginning Balance': begin_balance,
        'Principal Payment': principal_payment,
        'Interest Payment': interest_payment,
        'Total Payment': total_payment,
        'Ending Balance': end_balance
    })
    
    # Format numeric columns
    numeric_cols = ['Beginning Balance', 'Principal Payment', 
                    'Interest Payment', 'Total Payment', 'Ending Balance']
    df[numeric_cols] = df[numeric_cols].round(2)
    
    return df

# Generate Straight-Line Amortization Schedule
straight_schedule = straight_line_amortization(
    principal=6000000, 
    annual_rate=0.24, 
    years=7
)

print("Straight-Line Amortization Schedule:")
print(straight_schedule.to_string(index=False))

# Save to CSV for reference
straight_schedule.to_csv('straight_line_amortization.csv', index=False)

Straight-Line Amortization Schedule:
 Payment Number  Beginning Balance  Principal Payment  Interest Payment  Total Payment  Ending Balance
              1         6000000.00          857142.86        1440000.00     2297142.86      5142857.14
              2         5142857.14          857142.86        1234285.71     2091428.57      4285714.29
              3         4285714.29          857142.86        1028571.43     1885714.29      3428571.43
              4         3428571.43          857142.86         822857.14     1680000.00      2571428.57
              5         2571428.57          857142.86         617142.86     1474285.71      1714285.71
              6         1714285.71          857142.86         411428.57     1268571.43       857142.86
              7          857142.86          857142.86         205714.29     1062857.14           -0.00

In [3]:
import pandas as pd
import numpy as np

def annuity_amortization(principal, annual_rate, years):
    """
    Create an annuity amortization schedule
    
    Args:
    principal (float): Total loan amount
    annual_rate (float): Annual interest rate
    years (int): Loan tenure in years
    
    Returns:
    pandas.DataFrame: Amortization schedule
    """
    # Calculations
    periods = years
    monthly_rate = annual_rate / 12
    
    # Calculate fixed monthly payment
    monthly_payment = principal * (monthly_rate * (1 + monthly_rate)**(periods*12)) / ((1 + monthly_rate)**(periods*12) - 1)
    
    # Initialize lists to store schedule data
    payment_num = []
    begin_balance = []
    principal_payment = []
    interest_payment = []
    total_payment = []
    end_balance = []
    
    # Current balance starts at principal
    current_balance = principal
    
    for period in range(1, periods * 12 + 1):
        # Interest for the period
        interest = current_balance * monthly_rate
        
        # Principal payment is total payment minus interest
        current_principal = monthly_payment - interest
        
        # Track data
        payment_num.append(period)
        begin_balance.append(current_balance)
        principal_payment.append(current_principal)
        interest_payment.append(interest)
        total_payment.append(monthly_payment)
        
        # Reduce balance
        current_balance -= current_principal
        end_balance.append(current_balance)
    
    # Create DataFrame
    df = pd.DataFrame({
        'Payment Number': payment_num,
        'Beginning Balance': begin_balance,
        'Principal Payment': principal_payment,
        'Interest Payment': interest_payment,
        'Total Payment': total_payment,
        'Ending Balance': end_balance
    })
    
    # Format numeric columns
    numeric_cols = ['Beginning Balance', 'Principal Payment', 
                    'Interest Payment', 'Total Payment', 'Ending Balance']
    df[numeric_cols] = df[numeric_cols].round(2)
    
    return df

# Generate Annuity Amortization Schedule
annuity_schedule = annuity_amortization(
    principal=6000000, 
    annual_rate=0.24, 
    years=7
)

print("Annuity Amortization Schedule (First and Last 5 Payments):")
# Display first and last 5 payments
display_schedule = pd.concat([
    annuity_schedule.head(), 
    annuity_schedule.tail()
])
print(display_schedule.to_string(index=False))

# Save to CSV for reference
annuity_schedule.to_csv('annuity_amortization.csv', index=False)

# Additional Summary
print("\nSummary:")
print(f"Total Payments: {len(annuity_schedule)}")
print(f"Monthly Payment: ${annuity_schedule['Total Payment'].iloc[0]:.2f}")
print(f"Total Interest Paid: ${annuity_schedule['Interest Payment'].sum():.2f}")

Annuity Amortization Schedule (First and Last 5 Payments):
 Payment Number  Beginning Balance  Principal Payment  Interest Payment  Total Payment  Ending Balance
              1         6000000.00           28054.87         120000.00      148054.87      5971945.13
              2         5971945.13           28615.97         119438.90      148054.87      5943329.16
              3         5943329.16           29188.29         118866.58      148054.87      5914140.87
              4         5914140.87           29772.05         118282.82      148054.87      5884368.82
              5         5884368.82           30367.49         117687.38      148054.87      5854001.33
             80          697850.64          134097.86          13957.01      148054.87       563752.78
             81          563752.78          136779.82          11275.06      148054.87       426972.97
             82          426972.97          139515.41           8539.46      148054.87       287457.55
             83          287457.55          142305.72           5749.15      148054.87       145151.83
             84          145151.83          145151.83           2903.04      148054.87            0.00

Summary:
Total Payments: 84
Monthly Payment: $148054.87
Total Interest Paid: $6436609.19

In [ ]:
def calculate_emi(principal, annual_rate, years):
    # Monthly interest rate
    monthly_rate = annual_rate / 12 / 100
    
    # Total number of months
    num_months = years * 12
    
    # EMI Calculation
    emi = principal * monthly_rate * (1 + monthly_rate)**num_months / ((1 + monthly_rate)**num_months - 1)
    
    # Total amount payable
    total_payable = emi * num_months
    
    # Total interest
    total_interest = total_payable - principal
    
    return {
        'Monthly EMI': round(emi, 2),
        'Total Payable': round(total_payable, 2),
        'Total Interest': round(total_interest, 2)
    }

# Calculate EMI
result = calculate_emi(165000, 11.4, 3)
print("EMI Calculation Details:")
for key, value in result.items():
    print(f"{key}: ₹{value:,.2f}")

EMI Calculation Details:
Monthly EMI: ₹5,433.20
Total Payable: ₹195,595.10
Total Interest: ₹30,595.10

In [19]:
import pandas as pd
import numpy as np

def generate_amortization_schedule(principal, annual_rate, years):
    # Monthly calculations
    monthly_rate = annual_rate / 12 / 100
    num_months = years * 12
    
    # Calculate EMI
    emi = principal * monthly_rate * (1 + monthly_rate)**num_months / ((1 + monthly_rate)**num_months - 1)
    
    # Initialize lists to store schedule data
    schedule = []
    remaining_balance = principal
    
    for month in range(1, num_months + 1):
        # Calculate interest for the month
        interest_payment = remaining_balance * monthly_rate
        
        # Calculate principal payment
        principal_payment = emi - interest_payment
        
        # Update remaining balance
        remaining_balance -= principal_payment
        
        # Store monthly details
        schedule.append({
            'Month': month,
            'EMI': emi,
            'Principal Payment': principal_payment,
            'Interest Payment': interest_payment,
            'Remaining Balance': max(0, remaining_balance)
        })
    
    # Create DataFrame
    df = pd.DataFrame(schedule)
    
    # Round numeric columns
    numeric_cols = ['EMI', 'Principal Payment', 'Interest Payment', 'Remaining Balance']
    df[numeric_cols] = df[numeric_cols].round(2)
    
    return df

# Generate full amortization schedule
amortization_df = generate_amortization_schedule(400000, 11, 4)

# Print selected portions of the schedule
print("First 5 Months:")
print(amortization_df.head().to_string(index=False))

print("\nLast 5 Months:")
print(amortization_df.tail().to_string(index=False))

print("\nSummary:")
print(f"Total Interest Paid: ₹{amortization_df['Interest Payment'].sum():.2f}")
print(f"Total Principal Paid: ₹{amortization_df['Principal Payment'].sum():.2f}")
print(f"Monthly EMI: ₹{amortization_df['EMI'].iloc[0]:.2f}")

# Optional: Save full schedule to CSV
amortization_df.to_csv('loan_amortization_schedule.csv', index=False)

First 5 Months:
 Month      EMI  Principal Payment  Interest Payment  Remaining Balance
     1 10338.21            6671.54           3666.67          393328.46
     2 10338.21            6732.70           3605.51          386595.76
     3 10338.21            6794.41           3543.79          379801.34
     4 10338.21            6856.70           3481.51          372944.65
     5 10338.21            6919.55           3418.66          366025.10

Last 5 Months:
 Month      EMI  Principal Payment  Interest Payment  Remaining Balance
    44 10338.21            9877.13            461.08           40422.27
    45 10338.21            9967.67            370.54           30454.59
    46 10338.21           10059.04            279.17           20395.55
    47 10338.21           10151.25            186.96           10244.30
    48 10338.21           10244.30             93.91               0.00

Summary:
Total Interest Paid: ₹96234.04
Total Principal Paid: ₹399999.98
Monthly EMI: ₹10338.21

In [ ]:
import pandas as pd
import numpy as np

def generate_amortization_schedule(principal, annual_rate, years):
    # Monthly calculations
    monthly_rate = annual_rate / 12 / 100
    num_months = years * 12
    
    # Calculate EMI
    emi = principal * monthly_rate * (1 + monthly_rate)**num_months / ((1 + monthly_rate)**num_months - 1)
    
    # Initialize lists to store schedule data
    schedule = []
    remaining_balance = principal
    
    for month in range(1, num_months + 1):
        # Calculate interest for the month
        interest_payment = remaining_balance * monthly_rate
        
        # Calculate principal payment
        principal_payment = emi - interest_payment
        
        # Update remaining balance
        remaining_balance -= principal_payment
        
        # Store monthly details
        schedule.append({
            'Month': month,
            'EMI': emi,
            'Principal Payment': principal_payment,
            'Interest Payment': interest_payment,
            'Remaining Balance': max(0, remaining_balance)
        })
    
    # Create DataFrame
    df = pd.DataFrame(schedule)
    
    # Round numeric columns
    numeric_cols = ['EMI', 'Principal Payment', 'Interest Payment', 'Remaining Balance']
    df[numeric_cols] = df[numeric_cols].round(2)
    
    return df

# Generate full amortization schedule
amortization_df = generate_amortization_schedule(220000, 11, 3)

def calculate_foreclosure(df, total_months, foreclosure_fee_percentage=0.0285):
    # Get the last month's balance (37th month)
    if total_months + 1 > len(df):
        remaining_balance = df['Remaining Balance'].iloc[-1]
    else:
        remaining_balance = df['Remaining Balance'].iloc[total_months]
    
    # Calculate foreclosure fee
    foreclosure_fee = remaining_balance * foreclosure_fee_percentage
    
    # Total foreclosure amount
    total_foreclosure_amount = remaining_balance + foreclosure_fee
    
    # Total interest paid until foreclosure
    total_interest_paid = df.loc[df['Month'] <= total_months, 'Interest Payment'].sum()
    
    return {
        'Remaining Balance': remaining_balance,
        'Foreclosure Fee (2.85%)': foreclosure_fee,
        'Total Foreclosure Amount': total_foreclosure_amount,
        'Total Interest Paid Until Foreclosure': total_interest_paid
    }

# Perform foreclosure calculation
foreclosure_details = calculate_foreclosure(amortization_df, 25)

print("Foreclosure Details:")
for key, value in foreclosure_details.items():
    print(f"{key}: ₹{value:,.2f}")

# Compare with continuing loan
total_payments = amortization_df['EMI'].sum()
print(f"\nTotal Payments if Continuing Loan: ₹{total_payments:,.2f}")

Foreclosure Details:
Remaining Balance: ₹124,587.61
Foreclosure Fee (2.85%): ₹3,550.75
Total Foreclosure Amount: ₹128,138.36
Total Interest Paid Until Foreclosure: ₹63,819.65

Total Payments if Continuing Loan: ₹471,437.64

In [18]:
import pandas as pd
import numpy as np

def generate_amortization_schedule(principal, annual_rate, years):
    # Monthly calculations
    monthly_rate = annual_rate / 12 / 100
    num_months = years * 12
    
    # Calculate EMI
    emi = principal * monthly_rate * (1 + monthly_rate)**num_months / ((1 + monthly_rate)**num_months - 1)
    
    # Initialize lists to store schedule data
    schedule = []
    remaining_balance = principal
    
    for month in range(1, num_months + 1):
        # Calculate interest for the month
        interest_payment = remaining_balance * monthly_rate
        
        # Calculate principal payment
        principal_payment = emi - interest_payment
        
        # Update remaining balance
        remaining_balance -= principal_payment
        
        # Store monthly details
        schedule.append({
            'Month': month,
            'EMI': emi,
            'Principal Payment': principal_payment,
            'Interest Payment': interest_payment,
            'Remaining Balance': max(0, remaining_balance)
        })
    
    # Create DataFrame
    df = pd.DataFrame(schedule)
    
    # Round numeric columns
    numeric_cols = ['EMI', 'Principal Payment', 'Interest Payment', 'Remaining Balance']
    df[numeric_cols] = df[numeric_cols].round(2)
    
    return df

def calculate_foreclosure(df, total_months, foreclosure_fee_percentage=0.02):
    # Get the last month's balance (37th month)
    if total_months + 1 > len(df):
        remaining_balance = df['Remaining Balance'].iloc[-1]
    else:
        remaining_balance = df['Remaining Balance'].iloc[total_months]
    
    # Calculate foreclosure fee
    foreclosure_fee = remaining_balance * foreclosure_fee_percentage
    
    # Total foreclosure amount
    total_foreclosure_amount = remaining_balance + foreclosure_fee
    
    # Total interest paid until foreclosure
    total_interest_paid = df.loc[df['Month'] <= total_months, 'Interest Payment'].sum()
    
    return {
        'Remaining Balance': remaining_balance,
        'Foreclosure Fee (2.85%)': foreclosure_fee,
        'Total Foreclosure Amount': total_foreclosure_amount,
        'Total Interest Paid Until Foreclosure': total_interest_paid
    }

# Generate full amortization schedule
amortization_df = generate_amortization_schedule(400000, 11, 4)

# Perform foreclosure calculation
foreclosure_details = calculate_foreclosure(amortization_df, 37)

# Total amount paid by foreclosing
emi_paid_till_foreclosure = amortization_df.loc[amortization_df['Month'] <= 37, 'EMI'].sum()
total_foreclosure_paid = emi_paid_till_foreclosure + foreclosure_details['Total Foreclosure Amount']

# Compare with continuing loan
total_payments = amortization_df['EMI'].sum()
difference = total_payments - total_foreclosure_paid

# Display results
print("Foreclosure Details:")
for key, value in foreclosure_details.items():
    print(f"{key}: ₹{value:,.2f}")

print(f"\nTotal Payments if Continuing Loan: ₹{total_payments:,.2f}")
print(f"Total Amount Paid by Foreclosing: ₹{total_foreclosure_paid:,.2f}")
print(f"Difference Between Continuing Loan and Foreclosing: ₹{difference:,.2f}")

Foreclosure Details:
Remaining Balance: ₹98,355.47
Foreclosure Fee (2.85%): ₹1,967.11
Total Foreclosure Amount: ₹100,322.58
Total Interest Paid Until Foreclosure: ₹90,220.10

Total Payments if Continuing Loan: ₹496,234.08
Total Amount Paid by Foreclosing: ₹482,836.35
Difference Between Continuing Loan and Foreclosing: ₹13,397.73