In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
test={
    'science':[99,93,89,78],
    'social studies':[89,88,98,84],
    'math':[87,77,90,67]
}
sub=pd.DataFrame(test)
sub

   science  social studies  math
0       99              89    87
1       93              88    77
2       89              98    90
3       78              84    67

In [3]:
sub.sum(axis=0)

science           359
social studies    359
math              321
dtype: int64

In [4]:
sub.rename_axis(index='RollNo.',inplace=True)

In [5]:
sub.reset_index(inplace=True)

In [6]:
sub['RollNo.']=sub['RollNo.'].shift(-1)

In [7]:
sub['RollNo.']=np.where(sub['RollNo.'].isna(),sub['RollNo.'].ffill()+1,sub['RollNo.'])

In [8]:
sub

   RollNo.  science  social studies  math
0      1.0       99              89    87
1      2.0       93              88    77
2      3.0       89              98    90
3      4.0       78              84    67

In [9]:
sub['RollNo.']=sub['RollNo.'].astype('int32')

In [10]:
sub

   RollNo.  science  social studies  math
0        1       99              89    87
1        2       93              88    77
2        3       89              98    90
3        4       78              84    67

In [11]:
sub_melt=pd.melt(sub,id_vars='RollNo.',var_name='Subjects',value_name='Score')
sub_melt

    RollNo.        Subjects  Score
0         1         science     99
1         2         science     93
2         3         science     89
3         4         science     78
4         1  social studies     89
5         2  social studies     88
6         3  social studies     98
7         4  social studies     84
8         1            math     87
9         2            math     77
10        3            math     90
11        4            math     67

In [12]:
sub_melt['Score'].values

array([99, 93, 89, 78, 89, 88, 98, 84, 87, 77, 90, 67])

In [13]:
fig=px.line(sub_melt,x=sub_melt['RollNo.'],y=sub_melt['Score'],markers=True,color=sub_melt['Subjects'])
fig.update_layout(
    xaxis=dict(type='category'),
    title_text="Score by Roll Number and Subject",
    xaxis_title="Roll Number",
    yaxis_title="Score"
)
fig.show()

In [16]:
fig2=px.bar(sub_melt,x='RollNo.',y='Score',color='Subjects',barmode='group',
                color_discrete_sequence=px.colors.qualitative.Pastel2)
fig2.update_layout(
    xaxis=dict(type='category'),
    title_text="Score by Roll Number and Subject",
    xaxis_title="Roll Number",
    yaxis_title="Score"
)
fig2.show()